apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-go-sample
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/env: iterate
    app.kubernetes.io/part-of: tap-go-sample
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/warroyo/tap-go-sample
      ref:
        branch: main
